openapi: 3.0.0
info:
  title: Portfolio Web App
  description: Portfolio Service APIs.
  version: 0.1.9
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /:
    get:
      summary: Returns the portfolio website.
      responses:
        '200':    # status code
          description: Count of website visits
          content:
            text/plain:
              schema:
                type: string
